spring:
  application:
    name: jira-task-creator

jira:
  url: ${JIRA_URL}
  username: ${JIRA_USERNAME}
  token: ${JIRA_TOKEN}
  api:
    version: 3
    connect-timeout: 10000
    read-timeout: 30000

logging:
  level:
    org.jtc: DEBUG
    io.restassured: DEBUG
  file:
    name: .logs/jtc.log
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 10
